GET http://localhost:3000/songs

### Find song by Id
GET http://localhost:3000/songs/1

###  Create new song
POST http://localhost:3000/songs

### Update songs request
PUT http://localhost:3000/songs/1

### Delete song by Id
DELETE  http://localhost:3000/songs/1